version: '3'
services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DEFAULT_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    networks:
      - mynet
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  nacos:
    image: nacos/nacos-server:v2.1.2
    container_name: mynacos
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      MODE: standalone
    networks:
      - mynet
  ldap:
    image: osixia/openldap:latest
    container_name: cloud-ldap
    environment:
      LDAP_DOMAIN: myorg.com
      LDAP_ADMIN_PASSWORD: adminpassword
      LDAP_ORGANISATION: "My Organization"
    ports:
      - "389:389"
      - "636:636"
    networks:
      - mynet
    command:
      - '--copy-service'
    volumes:
     - ./init.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/init.ldif



  ldap-admin:
    image: osixia/phpldapadmin:latest
    container_name: cloud-phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: cloud-ldap # 使用服务名称 'ldap' 作为主机名
      PHPLDAPADMIN_HTTPS: "true"
    ports:
     -   "6443:443"
    networks:
      - mynet
    depends_on:
      - ldap

networks:
  mynet:
    driver: bridge