version: '3'
services:
  cloud-gateway:
    container_name: cloud-gatewayservice
    build:
      context: ./cloud-gateway/
      dockerfile: Dockerfile
    ports:
      - "7573:7573"
    networks:
      - mynet
    restart: on-failure

  cloud-oss:
    container_name: oss-service
    build:
      context: ./cloud-loginModule
      dockerfile: Dockerfile
    networks:
      - mynet
    restart: on-failure


  cloud-product:
    container_name: product-service
    build:
      context: ./cloud-productModule
      dockerfile: Dockerfile
    networks:
      - mynet
    restart: on-failure
networks:
  mynet:
    driver: bridge