spring:
  datasource:
    url: jdbc:mysql://101.33.230.121/test
    username: yangxiao
    password: yangxiao
  application:
    name: PRODUCTSERVICE
  cloud:
    nacos:
      discovery:
        server-addr: 101.33.230.121:8848

server:
  port: 8090

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.example.entity
jwt:
  # 密匙KEY
  secret: ADZf3m5uMBo0MatLfiE82QQNpow5LxT09fPYtdmGm6k3dSpJADZf3m5uMBo0MatLfiE82QQNpow5LxT09fPYtdmGm6k3dSpJ


