spring:
  datasource:
    url: jdbc:mysql://mysql/test
    username: root
    password: root
  application:
    name: PRODUCTSERVICE
  cloud:
    nacos:
      discovery:
        server-addr: mynacos:8848
  security:
    user:
      password: none

server:
  port: 8090

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.example.entity
jwt:
  # 密匙KEY
  secret: ADZf3m5uMBo0MatLfiE82QQNpow5LxT09fPYtdmGm6k3dSpJADZf3m5uMBo0MatLfiE82QQNpow5LxT09fPYtdmGm6k3dSpJ

